#!/bin/sh

set -e

case "$1" in
remove)
	rm -rf /usr/share/pmwiki/
	;;

upgrade)
	;;

purge)
	rm -rf /etc/pmwiki/
	;;

failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

*)
	echo "postrm called with unknown argument '$1'" >&2
	exit 1
	;;
esac


